cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #1f352b
selection_background  #b3ccbf
url_color             #68dbb0

color0   #131313
color1   #e54b58
color2   #7cd66e
color3   #dbc67b
color4   #24a172
color5   #5fa48a
color6   #68dbb0
color7   #abb2bf
color8   #5c6370
color9   #e05f6e
color10  #92e086
color11  #e8d697
color12  #82e8c0
color13  #308855
color14  #3f8673
color15  #ffffff
