cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #1f352b
selection_background  #b3ccbf
url_color             #68dbb0

color0   #131313
color1   #fb986a
color2   #67db6d
color3   #fff16b
color4   #4cd09f
color5   #036540
color6   #68dbb0
color7   #d7e5e0
color8   #838e8a
color9   #ffba9a
color10  #a1ffa5
color11  #fff6a1
color12  #85f0c8
color13  #a1ffdb
color14  #c2ffe8
color15  #f8fffc
