cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #21323e
selection_background  #b6c9d8
url_color             #83cfff

color0   #131313
color1   #e64c4a
color2   #73d66e
color3   #dbcf7b
color4   #3588bc
color5   #74a2bf
color6   #83cfff
color7   #abb2bf
color8   #5c6370
color9   #e05f62
color10  #8ae086
color11  #e8dd97
color12  #8bdeff
color13  #388599
color14  #577ba3
color15  #ffffff
