[config]

[templates.vicinae]
input_path = '/home/hiepnh/.config/matugen/templates/vicinae.toml'
output_path = '/home/hiepnh/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'
