general {
    lock_cmd = dms ipc call lock lock
    before_sleep_cmd = powerprofilesctl set power-saver; loginctl lock-session
    after_sleep_cmd = sleep 3s; powerprofilesctl set balanced
}

listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 360
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = powerprofilesctl set power-saver; niri msg action power-off-monitors
    on-resume = powerprofilesctl set balanced
}

listener {
    timeout = 1200
    on-timeout = systemctl suspend
}
