hl.config({
	plugin = {
		hyprwinview = {
			gap_size = 30,
			margin = 50,
			background = "rgba(00000000)",
			background_blur = 0,
			border_col = "rgba(ffffff33)",
			hover_border_col = "rgba(66ccffee)",
			border_size = 2,
			window_order = "natural", -- natural or none
			focus_scale = 1.05,
			show_app_icon = 1,
			app_icon_size = 24,
			app_icon_theme = "",
			app_icon_theme_source = "auto",
			app_icon_overrides = "",
			app_icon_position = "bottom right",
			app_icon_anchor_x = -1.0,
			app_icon_anchor_y = -1.0,
			app_icon_margin_x = 10,
			app_icon_margin_y = 10,
			app_icon_margin_relative_x = 0.0,
			app_icon_margin_relative_y = 0.0,
			app_icon_offset_x = 0,
			app_icon_offset_y = 0,
			app_icon_backplate_col = "rgba(00000066)",
			app_icon_backplate_padding = 6,
			show_window_text = 1,
			window_text_font = "Sans",
			window_text_size = 10,
			window_text_color = "rgba(ffffffff)",
			window_text_backplate_col = "rgba(00000099)",
			window_text_padding = 6,
			filter_animation_ms = 140,
			animation = "workspace_zoom", --  fade_scale, staggered, workspace_zoom, fade, or none
			animation_in_ms = 280,
			animation_out_ms = 220,
			animation_scale = 0.92,
			animation_stagger_ms = 16,
			animation_stagger_max_ms = 120,
			animation_workspace_zoom_stage_ratio = 0.38,
			animation_workspace_zoom_gap = 24,
		},
	},
})

hl.plugin.hyprwinview.configure({
	toggle_bar_cmd = "noctalia-shell ipc call bar toggle",
	ignore_titles = { "Wine System Tray", "webcam-mpv" },
	ignore_classes = { "keypop" },
	keys = {
		left = { "h", "left" },
		right = { "l", "right" },
		up = { "i", "k", "up" },
		down = { "m", "j", "down" },
		default_action = { "return", "o" },
		bring = { "b" },
		bring_replace = { "shift + b" },
		close = { "escape", "q" },
		filter_toggle = { "/" },
		filter_close = { "escape" },
		filter_bring = { "ctrl+b" },
		filter_bring_replace = { "ctrl+shift+b" },
		filter_left = { "left" },
		filter_right = { "right" },
		filter_up = { "up", "ctrl+p" },
		filter_down = { "down", "ctrl+n" },
	},
})
